// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: template.proto

package Node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenRingClient is the client API for TokenRing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenRingClient interface {
	// Passes the token to the next node
	PassToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Ack, error)
	// Requests access to the critical section
	RequestCriticalSection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Token, error)
	// Releases the critical section
	ReleaseCriticalSection(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Ack, error)
}

type tokenRingClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenRingClient(cc grpc.ClientConnInterface) TokenRingClient {
	return &tokenRingClient{cc}
}

func (c *tokenRingClient) PassToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/tokenring.TokenRing/PassToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenRingClient) RequestCriticalSection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/tokenring.TokenRing/RequestCriticalSection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenRingClient) ReleaseCriticalSection(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/tokenring.TokenRing/ReleaseCriticalSection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenRingServer is the server API for TokenRing service.
// All implementations should embed UnimplementedTokenRingServer
// for forward compatibility
type TokenRingServer interface {
	// Passes the token to the next node
	PassToken(context.Context, *Token) (*Ack, error)
	// Requests access to the critical section
	RequestCriticalSection(context.Context, *Empty) (*Token, error)
	// Releases the critical section
	ReleaseCriticalSection(context.Context, *Token) (*Ack, error)
}

// UnimplementedTokenRingServer should be embedded to have forward compatible implementations.
type UnimplementedTokenRingServer struct {
}

func (UnimplementedTokenRingServer) PassToken(context.Context, *Token) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassToken not implemented")
}
func (UnimplementedTokenRingServer) RequestCriticalSection(context.Context, *Empty) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCriticalSection not implemented")
}
func (UnimplementedTokenRingServer) ReleaseCriticalSection(context.Context, *Token) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCriticalSection not implemented")
}

// UnsafeTokenRingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenRingServer will
// result in compilation errors.
type UnsafeTokenRingServer interface {
	mustEmbedUnimplementedTokenRingServer()
}

func RegisterTokenRingServer(s grpc.ServiceRegistrar, srv TokenRingServer) {
	s.RegisterService(&TokenRing_ServiceDesc, srv)
}

func _TokenRing_PassToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenRingServer).PassToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenring.TokenRing/PassToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenRingServer).PassToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenRing_RequestCriticalSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenRingServer).RequestCriticalSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenring.TokenRing/RequestCriticalSection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenRingServer).RequestCriticalSection(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenRing_ReleaseCriticalSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenRingServer).ReleaseCriticalSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenring.TokenRing/ReleaseCriticalSection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenRingServer).ReleaseCriticalSection(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenRing_ServiceDesc is the grpc.ServiceDesc for TokenRing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenRing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenring.TokenRing",
	HandlerType: (*TokenRingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PassToken",
			Handler:    _TokenRing_PassToken_Handler,
		},
		{
			MethodName: "RequestCriticalSection",
			Handler:    _TokenRing_RequestCriticalSection_Handler,
		},
		{
			MethodName: "ReleaseCriticalSection",
			Handler:    _TokenRing_ReleaseCriticalSection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}
